version: 2.1

jobs:
  noop:
    docker:
      - image: cimg/python:3.7
    steps:
      - run: echo "noop"

workflows:
  noop:
    jobs:
      - noop:
          filters:
            branches:
              ignore: /.*/
